template: 'home.html'
projects:
  - header: "StaticPy"
    description:
      "StaticPy a static site generator built with Python Flask supporting Pandoc and Mathjax."
    view_details: "#"
  - header: "Project 2"
    description:
      "Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo,
      tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
      Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui."
    view_details: "#"
  - header: "Project 3"
    description:
      "Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo,
      tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
      Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui."
    view_details: "#"

posts:
  - 'posts/markdown-examples'
  - 'posts/mathjax-examples'